### PR TITLE
Boolean options should not go through the `self::escape` function.

### LINKED ISSUE #2392: Error returns code 0
- Deployer version:  7.0.0-beta.13
- Deployment OS: Ubuntu 20.04

I'm getting following error
>  TypeError  in Stringify.php on line 67:
>  Argument 1 passed to Deployer\Support\Stringify::escape() must be of the type string, bool given, called in phar:///home/circleci/app/bin/dep/src/Support/Stringify.php on line 35

See attached image:
Schermata da 2021-01-28 11-17-55

apart from weird error, I would expect that such case would return a code different from zero (otherwise I'm not able to notice that something went wrong)

### PR DESCRIPTION
**Pull request by cafferata**
Dump of [$input->getOptions()](https://github.com/deployphp/deployer/commit/18bdfc8bd94a8aa408f59dac1fb9daa6a8800c8c#diff-b872a77de62f6d05e055c5c2c19e0175ad4b9f4075531eee37dcba67a6d3cea8R20):

```php
array:18 [
  "tag" => null
  "revision" => null
  "branch" => null
  "option" => []
  "limit" => null
  "no-hooks" => false
  "plan" => false
  "start-from" => null
  "log" => null
  "profile" => null
  "help" => false
  "quiet" => false
  "verbose" => false
  "version" => false
  "ansi" => true
  "no-ansi" => false
  "no-interaction" => true
  "file" => null
]
```

```diff
            foreach ($option as $value) {
+                if(is_bool($value)){
+                    $options[] = "--$name";
+                    continue;
+                }
+
                $options[] = "--$name " . self::escape((string)$value);
            }
```

Output of `Stringify::options()` before/after:
```diff
-"--ansi 1 --decorated"
+"--ansi --decorated"
```

> Deployer\Support\Stringify::escape(): Argument #1 ($token) must be of type string, bool given

**Check list**

- [x] Bug fix #2392?
- [ ] ~~New feature?~~
- [ ] ~~BC breaks?~~
- [ ] ~~Deprecations?~~
- [x] Tests added?
- [x] Changelog updated?

### CODE REVIEW

File: test/src/Support/StringifyTest.php [hunk 1]
```diff
@@ -26,10 +26,11 @@ public function testOptions()
             new Option('start-from', null, Option::VALUE_REQUIRED, 'Start execution from this task'),
             new Option('log', null, Option::VALUE_REQUIRED, 'Write log to a file'),
             new Option('profile', null, Option::VALUE_REQUIRED, 'Write profile to a file',),
+            new Option('ansi', null, Option::VALUE_OPTIONAL, 'Force ANSI output',),
         ]);
 
-        self::assertEquals("--option 'env=prod' --limit 1 -vvv", Stringify::options(
-            new ArgvInput(['deploy', '-o', 'env=prod', '-l1'], $definition),
+        self::assertEquals("--option 'env=prod' --option ansi --limit 1 -vvv", Stringify::options(
```
Comment (antonmedv) [inline test/src/Support/StringifyTest.php:32]: I think second option is redundant.

Comment (cafferata) [reply test/src/Support/StringifyTest.php:32]: I tried following your feedback, but the [test output](https://github.com/deployphp/deployer/pull/2402/checks?check_run_id=1845210970) indicates otherwise.

Comment (cafferata) [reply test/src/Support/StringifyTest.php:32]: @antonmedv do you agree with my latest test case? Can we merge this merge request?

Comment (cafferata) [reply test/src/Support/StringifyTest.php:32]: Ping @antonmedv

Comment (antonmedv) [reply test/src/Support/StringifyTest.php:32]: Sure. Sorry for delay.

Comment (antonmedv) [reply test/src/Support/StringifyTest.php:32]: Actually unit tests are failing.

Comment (cafferata) [reply test/src/Support/StringifyTest.php:32]: This caused a rebase with master where the changelog was not sorted. Fixed.
